A <- read.table("household_power_consumption.txt", sep = ';', head = T, na.strings = '?')
library(dplyr)
elecdata <- filter(A,A$Date %in% c("1/2/2007", "2/2/2007"))
elecdata$DateTime <- strptime(paste(elecdata$Date, elecdata$Time, sep = ""), format = "%d/%m/%Y %H:%M:%S")
library(lubridate)
DateTime <- paste(elecdata$Date, elecdata$Time)
B <- dmy_hms(DateTime)
GAP2 <- as.numeric(elecdata[, "Global_active_power"])
png("Plot 2.png", height = 480, width = 480)
plot(B, GAP2, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
dev.off()
